# Generated by Django 5.1.1 on 2024-09-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=100)),
                ('mic_code', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('timestamp', models.IntegerField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent_change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_volume', models.BigIntegerField()),
                ('is_market_open', models.BooleanField()),
                ('f_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('f_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('f_low_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('f_high_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('f_low_change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('f_high_change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('f_range', models.CharField(max_length=50)),
            ],
        ),
    ]
